[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
jmbackend = { path = "../../" }
lazy_static = "1.4.0"
reqwest = { version = "0.11.9", features = ["rustls", "tokio-rustls", "rustls-tls"], default-features = false }
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
serde_json = "1.0.93"
warp = "0.3.2"
tokio = { version = "1.26.0", features = ["full"] }

[lib]
crate-type = ["staticlib"]
